name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        #{context.event.commits[0].message} == "11.17 testing"
        #context.event.head_commit.message
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
        #[{message}]
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
        #["11.17 testing"]
      - name: head commit
        if: contains(github.event.head_commit.message, '#skip')
        env:
          HEAD_COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$HEAD_COMMIT_MESSAGE"
        #print if there's #skip